### PR TITLE
Fix regression when options are omitted

### LINKED ISSUE #29: `await tmp.dir()` returns a string now.
https://github.com/benjamingr/tmp-promise/blob/6bd19f9e42d004fc10f1dc84aa5be1045b1e543a/index.js#L25-L30

I think this is what is happening here is this:

`promisify` will always pass its promise-resolving callback function _after_ the caller's last argument. Calling `tmp-promise`'s `tmp.dir` without an `options` argument will cause `promisify` to pass its callback function as the _first_ arg (`options` here), since the first arg is also the final arg.

When `tmp.dir` is given a function as it's _first_ arg, as is done here when `options` is not provided, it uses that argument as the callback function. 

This means the callback function `tmp-promise` provides as the second argument to `tmp.dir` is never called.

### PR DESCRIPTION
**Pull request by paulmelnikow**
Closes #29

### CODE REVIEW

**Comment by paulmelnikow** [comment]
It occurred to me when testing this that we should promisify the callback function. Do you see any reason not to ship that in 2.0.1?

**Comment by benjamingr** [comment]
> It occurred to me when testing this that we should promisify the callback function. Do you see any reason not to ship that in 2.0.1?

What do you mean? I didn't quite understand what you meant there.

**Comment by benjamingr** [comment]
@paulmelnikow ping ;)

**Comment by paulmelnikow** [comment]
Oops, I meant the `cleanup` function (not the `callback` function).

We pass through the `cleanup` function from `tmp`, which is asynchronous, but it's in error-first callback style. Instead we should return a promisified `cleanup` function so it can simply be `await`ed or `.then()`'d when that's desired.

You can see how I'm doing `await promisify(cleanup)()` in the tests, which works. Though making `tmp` behave nicely to async users is the concern of this library, so the caller shouldn't have to do that.

**Comment by benjamingr** [comment]
Sounds good to me.

**Pull request merged**
