### PR TITLE
replace mkstemps with mkstemp

### PR DESCRIPTION
**Pull request by thefourtheye**
The ~~syntax~~ signature resembles `mkstemp`, not `mkstemps`

### CODE REVIEW

**Comment by thefourtheye** [comment]
Okay, I had to rebase this as #1 landed :D. Its done now.

**Comment by benjamingr** [comment]
@thefourtheye I have to keep compatibility with https://github.com/raszi/node-tmp

**Comment by thefourtheye** [comment]
I submitted a patch there https://github.com/raszi/node-tmp/pull/77. Let's see if it gets through.

**Comment by benjamingr** [comment]
Ok, leaving open to track

**Comment by thefourtheye** [comment]
@benjamingr The other PR got accepted :-)

**Comment by benjamingr** [comment]
Great, can you add it to the code as another name of the old one and keep the old one (in code, not docs) for BC?

**Comment by benjamingr** [comment]
nevermind, I'll do it.

**Comment by benjamingr** [comment]
Wait, it's not actually a function - just a reference, lol, thanks :)

**Comment by thefourtheye** [comment]
@benjamingr Thanks :-) Yes, the function name was correct only.

**Pull request merged**
