### PR TITLE
Set up CircleCI

### PR DESCRIPTION
**Pull request by paulmelnikow**
This is an alternative to for #15 / #12. See my comment at https://github.com/benjamingr/tmp-promise/issues/12#issuecomment-490137928.

I tested and iterated on this in my fork and you can see the successful run here: https://circleci.com/gh/paulmelnikow/tmp-promise/7.

To take advantage of this, you'd need to sign up for CircleCI yourself, and tell it to start building this repo:

https://circleci.com/docs/2.0/first-steps/

There isn't a way to delegate that without transferring the repo into a GitHub organization.

After you do that, I think this PR branch might build on its own. If not I can push another commit which should trigger the build.

### CODE REVIEW

**Comment by benjamingr** [comment]
Looks good to me - maybe add a badge to the readme?

I already use circle for a bunch of things - I'll try to get this set up when I'm back from DevDays thanks.

**Comment by paulmelnikow** [comment]
Hey Benjamin, could you turn this on?

**Comment by benjamingr** [comment]
Sure, will configure it in circle

**Comment by benjamingr** [comment]
Added badge + configuration - thanks!

**Comment by benjamingr** [comment]
Also released 2.0.1

**Comment by paulmelnikow** [comment]
Thanks!

**Pull request merged**
